language: java
sudo: false
jdk:
- openjdk11
env:
  global:
  - secure: "SvqhJ7cFF4Uir0rvngiZAsxhgYAFCdw1bVHfKtA2MAV5taAuGsN0Uij+kLUP0oxHmrKwbSoOlHmTOG6m6GYOmX9ALAgfVRI41vnZxzhhR6zdHq4Kx84rhIxGHAXhxY8GPJiN+ClyeEr/qf6Jb60XyydU7w1wO8a1y+AYSW/CK0HZ4qORVgHOmfMmP7sCmgaPwCCcNoq/5mW873XHbJUbVh4d0wNn6Pej9oKRgsShWCqb/ihQ4IqNQjSQO+nF9FAuqMVzFJhnoNempuHG6R98QUlHXZ4IERlYfWfwjg6OtXk369QMAbQQ3k8bheozgM7R1mRq/cfIyIWzqY29UjqGVChy918QvXLDpLtVeU8ThF5cPgsle8K2NdaHZutfYXFo7qVosIAAMwkory5WN+RX7W2DqXAFwZjn5SfHvPMTz3tFgvAfVkV3qQg/bdOI6vA1cLghd/ZPRiCoJVJ/EdxwDor/FH5wRW2XFPIkqSWjlv4TnAd8YoAUZ44iO0DyUgyrB6oVdNYhW+0ei0M181rkSLdg5yfDykQF324lIwMwoalDMK4LcTxcgFVdyLSZr0xVtJr9vmr3w2xoJfB18hufHKkqMZQ+kDlhAmAjZApmrAIRR22gqhJJNctTEbX4O2s2BbD93TuKhBQMMDYzfoM8s62NCQ3qUbPtQUECW5HbF+k=" # CODACY_PROJECT_TOKEN
  - secure: "Ut9OdUpvJv9VIGQ7XLEhnBF1mvAFyZS32ODm0BuNdFgIYloglwzmpKtFzBTXNI6LxTyIDn+7yO4a3RJUT3np2BUQ2oLK0v2onMXjVpefq8V+Xo1hqYS5v5noBZhECfXD2KSo6oezS2hmFUEswJgLPp0fAGCJcLWhphqbzfBwWb39RorZ7ZHyxIdcx1KoKTzX/YDCl5Uepa3X4dg2Ak66Arhgf1jww3b0wlEkZky3jpqnICeHZVBz5M23kR9C9tj/j6QLT/bOYyMmaQ7niaa1DSmaeUSOQStp7jPwVG3fZvP1lFTIG4AmOxowHuRF+TlHM2PAAuPZrBh6xlshhx/V+6J6MWEtvt2wno1+DHbcIKvwb44No/w4mLhM+mejllv5DcGnEWJCam6qYRbuzXgx8ZX8G5nFLib260/UPt7PHndDEri1WqSUM8NIU8EkxbO6oNznTZ3OxmFPbJmJYutSVQsKwkURPR7ZHIGFHiBaVgT1uQm7rdtgBN7gA+9BjiS7WWAMFwFoxycQgnLvgM0mfJgdAbNzBLshPbSRK5Ea/j6czxKXNfXzl8GYEZwxtXPTDI8pT8fQMlXGOOgB+1SrbYWvlxV7KmOlrz3de+ziDNVDvzigWcm1zTL9RLFDl6K3FP6uer/Xs1KBf6sIlXmMnQ6Pp9afOMAMMKb7vhm8Xn4=" # BINTRAY_API_KEY
install:
- curl -o $HOME/.m2/settings.xml https://gist.githubusercontent.com/cryptobot/cf5fbd909c4782aaeeeb7c7f4a1a43da/raw/082261a990b96dcb3e9a3ddb96fc4c2e493f62c0/settings.xml
- mvn dependency:go-offline -Pdependency-check,coverage,release
script:
- mvn clean test jacoco:report verify -Dsurefire.useFile=false -Pcoverage
after_success:
- curl -o ~/codacy-coverage-reporter.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar
- $JAVA_HOME/bin/java -jar ~/codacy-coverage-reporter.jar report -l Java -r target/site/jacoco/jacoco.xml
cache:
  directories:
  - $HOME/.m2
deploy:
- provider: script # RELEASES
  script: mvn clean versions:set -DnewVersion=${TRAVIS_TAG} deploy -DskipTests -Prelease
  skip_cleanup: true
  on:
    repo: cryptomator/fuse-nio-adapter
    tags: true
after_deploy:
  - "echo '{\"close\": \"1\"}' | curl -v -X POST -u cryptobot:${BINTRAY_API_KEY} https://api.bintray.com/maven_central_sync/cryptomator/maven/fuse-nio-adapter/versions/${TRAVIS_TAG}"
